### ISSUE TITLE
GetText()

### ISSUE THREAD

**Issue by Rylazius** [ItzzExcel/luau-monaco#1]

**Comment by Rylazius** [comment]
Get text and editor.getvalue() function turns new line into \n

**Comment by ItzzExcel** [comment]
Always, you're getting the value, not the content.
You have to deserialize the JSON that it provides.

Example in C#:
```cs
var script = "monaco.editor.getModels()[0].getValue()";
var result = await CoreWebView2.ExecuteScriptAsync(script);
var text = JsonConvert.DeserializeObject<string>(result);
```

**Comment by Rylazius** [comment]
Ok ill try

**Comment by Rylazius** [comment]
The \n bug was fixed but i ran into another problem when running DEX
![image](https://github.com/ItzzExcel/luau-monaco/assets/94881672/6402e8c5-929d-4b4e-a759-6e5b8e4422e6)

**Comment by ItzzExcel** [comment]
Could you please reference from this.
https://github.com/ItzzExcel/LInjector/blob/v01.07.2023a/LInjector/Forms/application.cs#L253C13-L253C13

**Comment by ItzzExcel** [comment]
```cs
 string script = "monaco.editor.getModels()[0].getValue()";
var result = await webView2.CoreWebView2.ExecuteScriptAsync(script);
string scriptString = Newtonsoft.Json.JsonConvert.DeserializeObject<string>(result);

Executin.Exec(scriptString);
```

**Comment by Rylazius** [comment]
my code is same
`
            var script = "monaco.editor.getModels()[0].getValue()";
            var result = await MonacoEditor.ExecuteScriptAsync(script);
            var text = JsonConvert.DeserializeObject<string>(result);
            // execute function
`

**Comment by ItzzExcel** [comment]
Are you using editor.setValue to set the script into editor?

**Comment by Rylazius** [comment]
Yes

**Comment by ItzzExcel** [comment]
Your SetText function should be like this:
```cs
public async void SetText(string text)
{   
    text = text.Replace("\\", "\\\\");
    await CoreWebView2.ExecuteScriptAsync("editor.setValue('');");
    await CoreWebView2.ExecuteScriptAsync($"editor.setValue(`{text.Replace("`", "\\`")}`)");
}
```

**Comment by Rylazius** [comment]
Ohh ok

**Comment by Rylazius** [comment]
Thanks it is working rn

**Comment by ItzzExcel** [comment]
No problem!
